import type { FastifyInstance } from 'fastify';

/**
 * Register request ID propagation on every response.
 * The request ID is generated by Fastify's genReqId option and made
 * available as `request.id`. This hook copies it to the X-Request-Id
 * response header for client-side debugging and support.
 */
export function registerRequestId(app: FastifyInstance): void {
  app.addHook('onSend', async (request, reply) => {
    void reply.header('X-Request-Id', request.id);
  });
}
